### ISSUE TITLE
Add RSS/Atom feed to follow your blog

### ISSUE THREAD

**Issue by imdj** [davesnx/sancho.dev#696]
I found a mention of `feed.xml` in sitemap.js  but it appears the page itself doesn't exist?
https://github.com/davesnx/sancho.dev/blob/0c9cf1411fb1d1c84be349e42df7e07a25ddbc47/scripts/sitemap.js#L46

I'm interested in following your blog and figured opening an issue would be an easy way to be notified when that happens.

**Comment by davesnx** [comment]
Thanks @imdj. I never bother making a sitemap/feed. I will consider, thanks for opening the issue! 

I usually post new updates in my twitter: https://x.com/davesnx

**Comment by davesnx** [comment]
Pushed and update with an rss: https://sancho.dev/rss.xml

Let me know if it works good, and I can close this issue.

Again, thanks for opening the issue.

**Comment by imdj** [comment]
Great. Some insights from the current version:
- Limit the feed to `/blog` posts
- Reverse chronological, so new content appears at the top
- Add useful metadata like `title` to entries (I see you're already working on this)
- Make the website RSS feed more discoverable by adding it to html head like so:
```html
<link rel="alternate" type="application/rss+xml" title="davesnx's personal blog" href="https://sancho.dev/rss.xml">
```

**Comment by imdj** [comment]
Feel free to merge/edit my PR that fix the failing build and implement the changes mentioned previously.
I'll close the issue.
